services:
  postgres:
    container_name: local_database_keycloak
    image: postgres:15.2
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    restart: unless-stopped

  keycloak:
    image: jboss/keycloak:16.1.1
    depends_on:
      - postgres
    container_name: local_service_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8080:8080"
    restart: unless-stopped
